server:
  port: 8080

spring:
  application:
    name: auth

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  redis:
    host: localhost
    port: 6379

#  mvc:
#    throw-exception-if-no-handler-found: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.dayi.entity
  configuration:
    # can get id while saving data
    use-generated-keys: true
